config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'

  resources :recipes, only: %i[index show new create edit update destroy] do
    get 'all', on: :collection
    get 'featured', to: 'recipes#featured'
    post 'add_to_list', to: 'recipes#add_to_list', as: 'to_list'
  end
  resources :recipe_types, only: %i[show new create edit update destroy]
  resources :cuisines, only: %i[show new create edit update destroy]
  resources :users, only: %i[show new create edit update destroy]
  resources :recipe_lists, only: %i[show new create edit update destroy] do
    delete :delete_recipe, to: 'recipe_lists#delete_recipe'
  end
  get 'search', to: 'recipes#search' 

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :recipes, only: %i[show create update destroy] do
        get 'all', on: :collection
      end

      resources :cuisines, only: %i[index]
      resources :recipe_types, only: %i[index]
      resources :users, only: %i[show create update destroy]
      resources :sessions, only: %i[create destroy]
    end
  end
end

app/models/recipe_list.rb
class RecipeList < ApplicationRecord
  belongs_to :user
  has_many :recipe_sets, dependent: :destroy
  has_many :recipes, through: :recipe_sets

  validates :name, presence: true

  def recipe?(recipe)
    return true if recipes.include? recipe

    false
  end
end

app/controllers/recipe_lists_controller.rb
class RecipeListsController < ApplicationController
  before_action :set_recipe_list,
                only: %i[show edit update destroy delete_recipe]
  before_action :authenticate_user!,
                only: %i[new create edit update destroy delete_recipe]
  before_action :verify_list_author, only: %i[edit update destroy delete_recipe]

  def show; end

  def new
    @recipe_list = RecipeList.new
    @recipes = Recipe.all
  end

  def create
    @recipe_list = current_user.recipe_lists.new(recipe_list_params)
    if @recipe_list.save
      redirect_to @recipe_list
    else
      @recipes = Recipe.all
      render :new
    end
  end

  def edit; end

  def update
    if @recipe_list.update(recipe_list_params)
      redirect_to @recipe_list
    else
      render :edit
    end
  end

  def destroy
    @recipe_list.destroy
    flash[:alert] = 'Lista de receitas excluída com sucesso'
    redirect_to root_path
  end

  def delete_recipe
    recipe = @recipe_list.recipes.find_by(id: params[:recipe_id])
    if recipe && @recipe_list.recipes.delete(recipe)
      flash[:notice] = 'Receita excluída com sucesso'
    else
      flash[:alert] = 'Erro ao tentar excluir receita'
    end
    render :show
  end

  private

  def recipe_list_params
    params.require(:recipe_list).permit(:name)
  end

  def set_recipe_list
    return @recipe_list = RecipeList.find(params[:id]) if params[:id]

    @recipe_list = RecipeList.find(params[:recipe_list_id])
  end

  def verify_list_author
    set_recipe_list
    redirect_to root_path unless current_user.author?(@recipe_list)
  end
end

app/views/recipe_lists/_form.html.erb
<% if recipe_list.errors.any? %>
  <% recipe_list.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<%= form_with model: recipe_list, local: true, class: 'mt-4' do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name, class: 'form-control col-md-6' %>
  </div>
  <%= f.submit t('.submit'), id: 'commit', class: 'btn btn-primary' %>
<% end %>

app/views/recipe_lists/edit.html.erb
<% if @recipe_list.errors.any? %>
  <% @recipe_list.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<%= form_with model: @recipe_list, local: true, class: 'mt-4' do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name, class: 'form-control col-md-6' %>
  </div>
  <%= f.submit t('.submit'), id: 'commit', class: 'btn btn-primary' %>
<% end %>

app/views/recipe_lists/new.html.erb
<%= render partial: 'form', locals: {recipe_list: @recipe_list,
                                     recipes: @recipes} %>

app/views/recipe_lists/show.html.erb
<% if @recipe_list.errors.any? %>
  <% @recipe_list.errors.full_messages do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<h1><%= @recipe_list.name %></h1>
<p>Criada por: <%= link_to @recipe_list.user.name, @recipe_list.user %></p>

<% if @recipe_list.recipes.any? %>
  <ul>
    <% @recipe_list.recipes.each do |recipe| %>
      <li id="<%= recipe.id %>">
        <%= link_to recipe.title, recipe %>
        <% if current_user.author?(@recipe_list) %>
          <%= link_to t('.delete'), recipe_list_delete_recipe_path(recipe_list_id: @recipe_list.id, recipe_id: recipe.id),
                                    method: :delete,
                                    class: 'btn btn-danger',
                                    id: 'delete' %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if current_user.author?(@recipe_list) %>
  <%= link_to 'Editar', edit_recipe_list_path(@recipe_list), class: 'btn btn-primary' %>
  <%= link_to 'Excluir', recipe_list_path(@recipe_list), method: :delete,
                                                         id: 'delete_list',
                                                         class: 'btn btn-danger' %>
<% end %>