config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'

  resources :recipes, only: %i[index show new create edit update destroy] do
    get 'all', on: :collection
    get 'featured', to: 'recipes#featured'
    post 'add_to_list', to: 'recipes#add_to_list', as: 'to_list'
  end
  resources :recipe_types, only: %i[show new create edit update destroy]
  resources :cuisines, only: %i[show new create edit update destroy]
  resources :users, only: %i[show new create edit update destroy]
  resources :recipe_lists, only: %i[show new create edit update destroy] do
    delete :delete_recipe, to: 'recipe_lists#delete_recipe'
  end
  get 'search', to: 'recipes#search' 

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :recipes, only: %i[show create update destroy] do
        get 'all', on: :collection
      end

      resources :cuisines, only: %i[index]
      resources :recipe_types, only: %i[index]
      resources :users, only: %i[show create update destroy]
      resources :sessions, only: %i[create destroy]
    end
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :recipe_type
  belongs_to :cuisine
  belongs_to :user

  has_many :recipe_sets, dependent: :nullify
  has_many :recipe_lists, through: :recipe_sets

  has_one_attached :photo

  validates :title, :difficulty, :recipe_type,
            :cuisine, :cook_time,
            :ingredients, :cook_method,
            presence: true

  def cook_time_min
    "#{cook_time} minutos"
  end
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  has_many :recipes, dependent: :restrict_with_exception

  validates :name, presence: true
  validates :name, uniqueness: { message: 'Tipo de receita já existente',
                                 case_sensitive: false }
end

app/controllers/api/v1/recipes_controller.rb
class Api::V1::RecipesController < Api::V1::ApplicationController
  before_action :authenticate_with_token!, only: %i[create destroy update]
  def all
    @recipes = Recipe.all
    if @recipes.any?
      render json: @recipes
    else
      render json: { message: t('errors.messages.recipe_not_found') },
             status: :not_found
    end
  end

  def create
    recipe = current_user.recipes.new(recipe_params)
    if recipe.save
      render json: recipe, status: :created
    else
      render json: { errors: recipe.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    recipe = current_user.recipes.find(params[:id])
    recipe.destroy
    head :no_content
  end

  def show
    recipe = Recipe.find(params[:id])
    render json: recipe
  rescue ActiveRecord::RecordNotFound
    render json: { message: t('errors.messages.recipe_not_found') },
           status: :not_found
  end

  def update
    recipe = current_user.recipes.find(params[:id])

    if recipe.update(recipe_params)
      render json: recipe, status: :ok
    else
      render json: { errors: recipe.errors }, status: :unprocessable_entity
    end
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id,
                                   :difficulty, :cook_time, :ingredients,
                                   :cook_method, :photo)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe,
                only: %i[show edit update destroy add_to_list featured]
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :verify_author, only: %i[edit update destroy]
  before_action :set_recipe_list, only: %i[add_to_list]
  before_action :user_admin?, only: %i[featured]

  def add_to_list
    if @recipe_list.recipe?(@recipe)
      flash.now[:alert] = "Essa receita já está na lista #{@recipe_list.name}"
    else
      @recipe_list.recipes << @recipe
      flash.now[:alert] = "Receita adiciona à lista #{@recipe_list.name}"
    end
    render :show
  end

  def index
    @latest_recipes = Recipe.last(6)
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
    @recipe_lists = RecipeList.all
  end

  def show; end

  def new
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      @recipe_types = RecipeType.all
      @cuisines = Cuisine.all
      render :new
    end
  end

  def edit
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      @recipe_types = RecipeType.all
      @cuisines = Cuisine.all
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    flash[:alert] = 'Receita excluída com sucesso'
    redirect_to root_path
  end

  def featured
    @recipe.featured = true
    @recipe.save
    redirect_to @recipe
  end

  def search
    @recipes = Recipe.where('title like ?', "%#{params[:search]}%")
  end

  def all
    @recipes = Recipe.all
    @recipe_types = RecipeType.all
    @cuisines = Cuisine.all
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id, :cuisine_id,
                                   :difficulty, :cook_time, :ingredients,
                                   :cook_method, :photo)
  end

  def set_recipe
    return @recipe = Recipe.find(params[:id]) if params[:id]

    @recipe = Recipe.find(params[:recipe_id])
  end

  def set_recipe_list
    @recipe_list = RecipeList.find(params[:list_id])
  end

  def verify_author
    set_recipe
    redirect_to root_path unless current_user.author?(@recipe)
  end
end

app/views/recipes/_form.html.erb
<% if recipe.errors.any? %>
  <p>Você deve informar todos os dados da receita</p>
<% end %>

<%= form_with model: recipe, local: true, class: 'mt-4' do |f| %>
  <div class="form-group">
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title, class: 'form-control col-md-6' %>
  </div>
  <div class="form-group">
    <%= f.label :recipe_type_id, 'Tipo da Receita' %>
    <%= f.collection_select :recipe_type_id, recipe_types, :id, :name, {}, class: 'form-control col-md-6' %>
  </div>
  <div class="form-group">
    <%= f.label :cuisine_id, 'Cozinha' %>
    <%= f.collection_select :cuisine_id, cuisines, :id, :name, {}, class: 'form-control col-md-6' %>
  </div>
  <div class="form-group">
    <%= f.label :difficulty, 'Dificuldade' %>
    <%= f.text_field :difficulty, class: 'form-control col-md-6' %>
  </div>
  <div class="form-group">
    <%= f.label :cook_time, 'Tempo de Preparo' %>
    <%= f.number_field :cook_time, class: 'form-control col-md-6' %>
  </div>
  <div class="form-group">
    <%= f.label :ingredients, 'Ingredientes' %>
    <%= f.text_field :ingredients, class: 'form-control col-md-6' %>
  </div>
  <div class="form-group">
    <%= f.label :cook_method, 'Como Preparar' %>
    <%= f.text_area :cook_method, class: 'form-control col-md-6' %>
  </div>
  <div class="form-group">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>
  <%= f.submit 'Enviar', class: 'btn btn-primary' %>
<% end %>

app/views/recipes/_recipe.html.erb
<div class="col-md-4 recipe">
  <div class="card mb-4 shadow-sm">
    <%= image_tag 'https://via.placeholder.com/500x255', class: 'card-img-top' %>
    <div class="card-body">
      <% if recipe.featured %>
        <h1 class="h4">
          <%= link_to recipe.title, recipe %>  <i class="fas fa-star"></i>
        </h1>
      <% else %>
        <h1 class="h4">
          <%= link_to recipe.title, recipe %>
        </h1>
      <% end %>
      <ul>
        <li><%= recipe.recipe_type.name %></li>
        <li><%= recipe.cuisine.name %></li>
        <li><%= recipe.difficulty %></li>
        <li><%= recipe.cook_time_min %></li>
      </ul>
    </div>
  </div>
</div>

app/views/recipes/all.html.erb
<div class="row">
  <aside class="col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item list-group-item-action">
        <h5>Tipos de receita</h5>
        <% if @recipe_types.any? %>
          <ul class="list-group list-group-flush">
          <% @recipe_types.each do |recipe_type| %>
            <li class="list-group-item list-group-item-action">
              <%= link_to recipe_type.name, recipe_type %>
            </li>
          <% end %>
          </ul>
        <% end %>
      </li>
      <li class="list-group-item list-group-item-action">
        <%= link_to 'Últimas receitas', root_path %>
      </li>
    </ul>
  </aside>
  <section id="all" class="col-md-9">
    <h3>Todas as receitas</h3> 
    <div class="row">
      <% if @recipes.any? %>
        <%= render partial: 'recipe', collection: @recipes %>
      <% end %>
    </div>
  </section>
</div>

app/views/recipes/edit.html.erb
<%= render partial: 'form', locals: { recipe: @recipe,
                                      recipe_types: @recipe_types,
                                      cuisines: @cuisines } %>

app/views/recipes/index.html.erb
<div class="row">
  <aside class="col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item list-group-item-action">
        <h5><%= t('activerecord.models.recipe_type.other')%></h5>
        <% if @recipe_types.any? %>
          <ul class="list-group list-group-flush">
          <% @recipe_types.each do |recipe_type| %>
            <li class="list-group-item list-group-item-action">
              <%= link_to recipe_type.name, recipe_type %>
            </li>
          <% end %>
          </ul>
        <% end %>
      </li>
      <li class="list-group-item list-group-item-action">
        <h5><%= t('activerecord.models.cuisine.other')%></h5>
        <% if @cuisines.any? %>
          <ul class="list-group list-group-flush">
          <% @cuisines.each do |cuisine| %>
            <li class="list-group-item list-group-item-action">
              <%= link_to cuisine.name, cuisine %>
            </li>
          <% end %>
          </ul>
        <% end %>
      </li>
      <li class="list-group-item list-group-item-action">
        <%= link_to 'Todas as receitas', all_recipes_path %>
      </li>
    </ul>
    <ul class="list-group list-group-flush">
      <li class="list-group-item list-group-item-action">
        <% if user_signed_in? %>
          <section id="lists">
            <h3 class="h5">Minhas listas</h3>
            <% if current_user.recipe_lists.any? %>
              <ul class="list-group list-group-flush">
                <% current_user.recipe_lists.each do |list| %>
                  <li class="list-group-item list-group-item-action"><%= link_to list.name, list %></li>
                <% end %>
              </ul>
            <% end %>
            <%= link_to 'Criar lista de receitas', new_recipe_list_path %>
          </section>
        <% end %>
      </li>
    </ul>
  </aside>

  <section id="latest" class="col-md-9">
    <h3>Últimas receitas</h3> 
    <div class="row">
      <% if @latest_recipes.any? %>
        <%= render partial: 'recipe', collection: @latest_recipes %>
      <% end %>
    </div>
  </section>
</div>

app/views/recipes/new.html.erb
<%= render partial: 'form', locals: { recipe: @recipe,
                                      recipe_types: @recipe_types,
                                      cuisines: @cuisines } %>

app/views/recipes/search.html.erb
<h1>Resultados da pesquisa</h1>

<% if @recipes.any? %>
  <%= render partial: 'recipe', collection: @recipes %>
<% else %>
  <p>Nenhuma receita encontrada.</p>
<% end %>

app/views/recipes/show.html.erb
<% if @recipe.featured %>
  <h1><%= @recipe.title %> <i class="fas fa-star"></i></h1>
<% else %>
  <h1><%= @recipe.title %></h1>
<% end %>

<% if @recipe.photo.attached? %>
  <%= image_tag @recipe.photo %>
<% end %>

<p>Criada por: <%= link_to @recipe.user.email, @recipe.user %></p>

<h3>Detalhes</h3>

<p><%= @recipe.recipe_type.name %></p>
<p><%= @recipe.cuisine.name %></p>
<p><%= @recipe.difficulty %></p>
<p><%= @recipe.cook_time %> minutos</p>

<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %></p>

<h3>Como Preparar</h3>
<p><%= @recipe.cook_method %></p>

<% if user_signed_in? && current_user.author?(@recipe) %>
  <%= link_to 'Editar', edit_recipe_path(@recipe), class: 'btn btn-primary' %>
  <%= link_to 'Excluir', @recipe, method: :delete, class: 'btn btn-danger' %>
<% end %>
<%= link_to 'Voltar', root_path, class: 'btn btn-secondary' %>

<!-- TODO Mudar para um select com todas as listas criadas -->
<% if user_signed_in? && current_user.recipe_lists.any? %>
  <% current_user.recipe_lists.each do |list| %>
    <%= link_to "Adicionar à lista #{list.name}", recipe_to_list_path(@recipe, list_id: list), method: :post %>
  <% end %>
<% end %>

<% if user_signed_in? && current_user.admin %>
  <%= link_to t('.featured'), recipe_featured_path(@recipe), id: 'featured',
                              class: 'btn btn-outline-warning ' %>
<% end %>