config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'

  resources :recipes, only: %i[index show new create edit update destroy] do
    get 'all', on: :collection
    get 'featured', to: 'recipes#featured'
    post 'add_to_list', to: 'recipes#add_to_list', as: 'to_list'
  end
  resources :recipe_types, only: %i[show new create edit update destroy]
  resources :cuisines, only: %i[show new create edit update destroy]
  resources :users, only: %i[show new create edit update destroy]
  resources :recipe_lists, only: %i[show new create edit update destroy] do
    delete :delete_recipe, to: 'recipe_lists#delete_recipe'
  end
  get 'search', to: 'recipes#search' 

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :recipes, only: %i[show create update destroy] do
        get 'all', on: :collection
      end

      resources :cuisines, only: %i[index]
      resources :recipe_types, only: %i[index]
      resources :users, only: %i[show create update destroy]
      resources :sessions, only: %i[create destroy]
    end
  end
end

app/views/shared/_header.html.erb
<section class="jumbotron text-center">
  <h1>CookBook</h1>
  <p>Bem-vindo ao maior livro de receitas online</p>
  <% if user_signed_in? %>
    <p class="text-center">
      Olá, <%= current_user.email %>
    </p>
  <% end %>
</section>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Cookbook', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'Home', root_path, class: 'nav-link'%>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Enviar uma receita', new_recipe_path, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Criar conta', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Entrar', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
      <% if user_signed_in? && current_user.admin %>
        <li class="nav-item">
          <%= link_to 'Cadastrar tipo de receita', new_recipe_type_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Cadastrar cozinha', new_cuisine_path, class: 'nav-link' %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= form_with url: search_path, method: :get, local: true, class: 'form-inline' do |f| %>
          <%= f.label :search, 'Buscar', class: 'navbar-text' %>
          <%= f.text_field :search, class: 'form-control ml-2' %>
          <%= f.submit 'Pesquisar', class: 'btn btn-primary ml-2' %>
        <% end %>
      </li>
    </ul>
    <% if user_signed_in? %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Meu perfil', user_path(current_user), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Editar perfil', edit_user_path(current_user), class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      </ul>
    <% end %>
  </div>
</nav>