config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'recipes#index'

  resources :recipes, only: %i[index show new create edit update destroy] do
    get 'all', on: :collection
    get 'featured', to: 'recipes#featured'
    post 'add_to_list', to: 'recipes#add_to_list', as: 'to_list'
  end
  resources :recipe_types, only: %i[show new create edit update destroy]
  resources :cuisines, only: %i[show new create edit update destroy]
  resources :users, only: %i[show new create edit update destroy]
  resources :recipe_lists, only: %i[show new create edit update destroy] do
    delete :delete_recipe, to: 'recipe_lists#delete_recipe'
  end
  get 'search', to: 'recipes#search' 

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :recipes, only: %i[show create update destroy] do
        get 'all', on: :collection
      end

      resources :cuisines, only: %i[index]
      resources :recipe_types, only: %i[index]
      resources :users, only: %i[show create update destroy]
      resources :sessions, only: %i[create destroy]
    end
  end
end

app/controllers/api/v1/recipe_types_controller.rb
class Api::V1::RecipeTypesController < Api::V1::ApplicationController
  def index
    @recipe_types = RecipeType.all
    if @recipe_types.any?
      render json: @recipe_types
    else
      render json: { message: t('errors.messages.recipe_type_not_found') },
             status: :not_found
    end
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  before_action :set_recipe_type, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :user_admin?, only: %i[new create edit update destroy]

  def new
    @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.new(recipe_type_params)
    if @recipe_type.save
      redirect_to @recipe_type
    else
      render :new
    end
  end

  def edit; end

  def update
    if @recipe_type.update(recipe_type_params)
      redirect_to @recipe_type
    else
      render :edit
    end
  end

  def destroy
    @recipe_type.destroy
    flash[:alert] = 'Tipo de receita excluído com sucesso'
    redirect_to root_path
  end

  def show; end

  private

  def recipe_type_params
    params.require(:recipe_type).permit(:name)
  end

  def set_recipe_type
    @recipe_type = RecipeType.find(params[:id])
  end
end

app/views/recipe_types/_form.html.erb
<% if recipe_type.errors.any? %>
  <% recipe_type.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

<%= form_with model: recipe_type, local: true, class: 'mt-4' do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Nome' %>
    <%= f.text_field :name, class: 'form-control col-md-6' %>
  </div>
  <%= f.submit t('.submit'), id: 'commit', class: 'btn btn-primary' %>
<% end %>

app/views/recipe_types/edit.html.erb
<%= render partial: 'form', locals: { recipe_type: @recipe_type} %>

app/views/recipe_types/new.html.erb
<%= render partial: 'form', locals: { recipe_type: @recipe_type } %>

app/views/recipe_types/show.html.erb
<h1><%= @recipe_type.name %></h1>

<% if @recipe_type.recipes.any? %>
  <div class="row">
    <%= render partial: 'recipes/recipe', collection: @recipe_type.recipes %>
  </div>
<% else %>
  <p>Não encontramos nenhuma receita desse tipo</p>
<% end %>

<% if user_signed_in? && current_user.admin %>
  <%= link_to t('edit'), edit_recipe_type_path(@recipe_type),
                         id: 'edit', class: 'btn btn-primary' %>
  <%= link_to t('delete'), recipe_type_path(@recipe_type),
                         method: :delete, id: 'delete',
                         class: 'btn btn-danger' %>
<% end %>